错误处理
=====


### 背景

本文主题是如何在 django 中处理异常，包含以下几部分

1. 当前各种语言处理错误的方式
2. 在 django 处理错误的最佳实践
3. 总结

### 不同语言处理错误

以除法运算为例，不能进行则返回 -1，我们比较一下 Python、Go、Rust 如何处理错误

#### Python 

第一种方式

```python


def divide(a: int, b: int):
	return a / b

def main():
	try:
		ret = divide(1, 0)
	except ZeroDivisionError:
		ret = -1

	print(ret)

if __name__ == "__main__":
	main()

```

如果我们不想写 `try...except` 结构，可以使用 `with` 来处理，引出第二种方式

```python

from contextlib import suppress

def divide(a: int, b: int):
	return a / b

def main():
	ret = -1
	with suppress(ZeroDivisionError):
		ret = divide(1, 0)
	print(ret)


if __name__ == "__main__":
	main()

```

接着我们看看 Go 语言的方式。

#### Go

```go

func divide(a, b float64) (float64, error) {
	if b == 0 {
		return 0, errors.New("cannot divide by zero")
	}
	return a / b, nil
}

func main() {
	ret, err := divide(1, 0)
	if err != nil {
		ret = -1
	}

	fmt.Println(ret)
}


```

在 Go 语言中，通常情况下函数的返回包含 err 值，然后上层函数在调用之后，先判断该函数的返回是否包含错误，有错误先处理。

接着我们继续看看 `Rust` 的错误

#### Rust

```rust


fn divide(a: f64, b: f64) -> Result<f64, &'static str> {
    if b == 0.0 {
        Err("Cannot divide by zero")
    } else {
        Ok(a / b)
    }
}

fn main() {
    let ret = match divide(1.0, 0.0) {
        Ok(i) => i,
        Err(_) => -1.0
    };
    // let ret = divide(1.0, 0.0).unwrap_or(-1.0);
    
    println!("ret: {}", ret)
}

```

在 Rust 中，通常情况下函数的返回为一个 `Result` 结构，包含正常以及错误值，在处理的时候使用 `match` 或者 `unwrap_or` 关键字继续处理。

总结下来，Python 把错误看作程序异常，抛出错误，谁捕获谁处理。而Go和Rust把错误看作正常返回，返回错误让上层处理。Go 和 Rust 都属于诞生时间不（那么）久，我想这也代表着编程语言领域怎么看待错误处理的趋势！

从而引出本文最重要的一个观点：**将错误当作程序的正常返回**，并将此理念应用到 Django 中。

### 在 Django 中处理错误


#### 传统处理方式

我们试想以下应用场景，一个json文件访问接口 `/api/file/view?file_path=xx/xx/xx.json` ，第一步是打开文件验证是否为 json 格式，然后需要将访问记录存储到 DB 中，最后在 redis 中对该文件总访问数进行 + 1 操作，正常返回为 `1000 - locate successfully` ，异常返回为 `2001 - file not exist` 、 `2002 - db insert error` 和 `2003 - redis error`

依此逻辑，我们编写的代码如下

`views.py`

```python

import json
import os

from django.core.cache import cache
from django.http import HttpRequest, JsonResponse

from .models import ViewRecord

class Code:
    SUCCESS = 1000
    FILE_NOT_FOUND = 2001
    FILE_NOT_JSON = 2002
    DB_ERROR = 2003
    REDIS_ERROR = 2004


def locate_file(request: HttpRequest) -> JsonResponse:
    file_path = request.GET.get("file_path")

    if not file_path or not os.path.exists(file_path):
        return JsonResponse({"msg": "File not found", "code": Code.FILE_NOT_FOUND})

    with open(file_path, "r") as f:
        content = f.read()
        try:
            json.loads(content)
        except json.JSONDecodeError:
            return JsonResponse({"msg": "File content is not valid json", "code": Code.FILE_NOT_JSON})

    try:
        ViewRecord.objects.create(file_path=file_path)
    except Exception:
        return JsonResponse({"msg": "Database error", "code": Code.DB_ERROR})

    cache_key = f"file_path_{file_path}"
    try:
        cache.incr(cache_key)
    except Exception:
        return JsonResponse({"msg": "Redis error", "code": Code.REDIS_ERROR})

    return JsonResponse({"msg": "Success", "code": Code.SUCCESS})



```

可以看到，整个代码被三个 `try...except` 充斥，整个代码的可读性堪忧，这里还只是例子，实际的业务代码会更难看一些，`try...except` 层层嵌套的情况并不罕见，但为了来保证程序能处理各种异常，这些 `try...except` 又是必不可少的一环。


那要怎么既保证代码在可读性ok，又保证程序不出问题呢，核心是借用 django 中间件机制


#### 中间件

在 django 中间件的说明中，存在 [process_exception](https://docs.djangoproject.com/en/5.0/topics/http/middleware/#process-exception) 钩子函数，代码结构如下

```python

class SimpleMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response
        # One-time configuration and initialization.

    def __call__(self, request):
        # Code to be executed for each request before
        # the view (and later middleware) are called.

        response = self.get_response(request)

        # Code to be executed for each request/response after
        # the view is called.

        return response

	def process_exception(request, exception):		
		pass

```

拥有 `process_exception` 方法的类能够处理此请求过程中任何 `raise` 出来的错误，在方法签名中， exception 参数被显式传递，这就符合了上一部分提到的将错误看作是程序正常返回的原则。

根据中间件的洋葱模型运行方式，只要将含有 `process_exception` 的中间件放在 `MIDDLEWARE` 的第一位，就能处理所有的异常情况了。

#### 实践

有了把错误看作正常返回的理念，和实现理念的中间件工具，结合起来我们就能完成代码了

第一步是定义一些 error，用作响应处理

`errors.py`

```python

class BaseError(Exception):
    msg = "Base error"
    code = 1000


class FileNotFound(BaseError):
    msg = "File not found"
    code = 2001


class FileNotJson(BaseError):
    msg = "File content is not valid json"
    code = 2002


class DbError(BaseError):
    msg = "Database error"
    code = 2003


class RedisError(BaseError):
    msg = "Redis error"
    code = 2004

```

然后再写一个 exception 转换函数，将 db 和 redis 相关错误转换到定义好的类上来

`errors.py`

```python

import json

from django.db import utils as django_db_utils


def translate_exception(exception: Exception) -> BaseError:
    if isinstance(exception, django_db_utils.Error):
        return DbError()
    elif isinstance(exception, RedisError):
        return RedisError()
    elif isinstance(exception, BaseError):
        return exception
    elif isinstance(exception, FileNotFoundError):
        return FileNotFound()
    elif isinstance(exception, json.JSONDecodeError):
        return FileNotJson()
    else:
        return BaseError()


```

接下来完成中间件的编写

```python

import typing as T

from django.http import HttpRequest, HttpResponse, JsonResponse

from . import errors as E


class ErrorMiddleware:
    def __init__(self, get_response: T.Callable) -> None:
        self.get_response = get_response

    def __call__(self, request: HttpRequest) -> HttpResponse:
        resp = self.get_response(request)

        return resp

    def process_exception(self, request: HttpRequest, exception: Exception) -> HttpResponse:
        new_exception = E.translate_exception(exception)
        return JsonResponse({"msg": new_exception.msg, "code": new_exception.code})


```

将该中间件置于 MIDDLEWARE 中第一个

`settings.py`

```python

MIDDLEWARE = [
    "topic_error.middlewares.ErrorMiddleware"
    # ...
]


```

最后完成 `views.py`

```python

import json
import os

from django.core.cache import cache
from django.http import HttpRequest, JsonResponse
from topic_error import errors as E

from .models import ViewRecord


def locate_file(request: HttpRequest) -> JsonResponse:
    file_path = request.GET.get("file_path")

    if not file_path or not os.path.exists(file_path):
        raise E.FileNotFound()

    with open(file_path, "r") as f:
        content = f.read()
        json.loads(content)

    ViewRecord.objects.create(file_path=file_path)

    cache_key = f"file_path_{file_path}"
    cache.incr(cache_key)

    return JsonResponse({"msg": "Success", "code": 1000})


```


可以看到，新的写法有两个较大的改变

1. 不用再去特意关注异常出现，`try...except` 代码被中间件处理了
2. 在文件路径验证部分，甚至会直接 `raise` 错误出去，让中间件处理

这样做会代码以下好处

1、业务代码中大多数情况下，只用关注正常逻辑，忽略异常错误，对开发者开发体验是非常好的。极端情况下虽然仍避免不了使用 `try...except`，但这属于少数情况。
2、直接 raise 的写法同样对开发者编写友好，同时所有的错误在中间件中处理，对于监控埋点以及错误上报非常方便，监控代码和上报代码不用散落在各处。

关于第二点，会在监控以及错误上报相关的文章中提起。


### 总结

首先是转换看待错误的方式，需要将错误看作是程序正常的返回，这样在代码里能避免过多 `try...except` 出现，然后合理使用 django 中间件中的 `process_exception` 处理请求线程出现的错误。

最后在代码中按正常思路编写代码，遇到可遇见的异常时，直接将错误 raise 出去，让中间件捕获处理。

在整个 django 开发经验中，错误处理的思路转变受用程度可以排在所有文章中的前几位，非常推荐 django 开发者实践。

